### ISSUE TITLE
Example shadow components included?

### ISSUE THREAD

**Issue by asuh** [LekoArts/gatsby-starter-portfolio-emma#136]
At this moment, I'm new to Gatsby themes and starter themes. I read resources and tutorials but could not understand what was needed to update the theme elements like header and footer. A few hours over a few days of trial and error finally saw the result of shadowing a component file. Documentation for doing this is still fragmented over various articles and videos on the web which is why this was so confusing for me.

I like the preconfigured look of this starter theme and iterating on it means quick setup. However, I think it'd be very helpful for this and other starter themes to include either an example shadow component file or more explicit instructions in the README text. 

I could have saved much time by knowing the following structure, which isn't included, is needed for shadowing component files:
```[starter-theme-root]/src/@lekoarts/gatsby-theme-emma/components/[file-name].tsx```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

You're correct that there isn't any info on the docs, but in the tutorial:
FOO

Maybe you want to open an [issue on Gatsby's repo](https://github.com/gatsbyjs/gatsby/issues/new?template=feature_request.md) to explain your difficulties?

In the meantime, I plan to add better documentation. It just takes time to write good one:
https://github.com/LekoArts/gatsby-themes/issues/28
