### ISSUE TITLE
Error: Cannot find module '../build/Release/sharp.node'

### ISSUE THREAD

**Issue by SKempin** [LeKoArts/gatsby-starter-portfolio-emma#2]
I'm getting the following issue upon trying to `npm run dev` :
```
Steve@Stephens-MacBook-Pro Project-Name $ npm run dev

> gatsby-starter-portfolio-emma@1.0.0 dev /Users/Steve/Documents/Projects/Portfolio/Repository/Project-Name
> gatsby develop -o

success delete html files from previous builds — 0.007 s
success open and validate gatsby-config.js — 1.331 s
success copy gatsby files — 0.031 s
error UNHANDLED EXCEPTION


  Error: Cannot find module '../build/Release/sharp.node'

  - module.js:11 require
    internal/module.js:11:18

  - constructor.js:8 Object.<anonymous>
    [Project-Name]/[sharp]/lib/constructor.js:8:15

  - module.js:11 require
    internal/module.js:11:18

  - index.js:3 Object.<anonymous>
    [Project-Name]/[sharp]/lib/index.js:3:15


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-portfolio-emma@1.0.0 dev: `gatsby develop -o`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-starter-portfolio-emma@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Gatsby `1.9.108`

**Comment by jwgravesfl** [comment]
I have been trying to install run this for 12 hours today.  I have installed python, reinstalled...  sharp, images, set paths...  what a miserable day.

**Comment by LeKoArts** [comment]
If you added the plugin "gatsby-remark-copy-linked-files" maybe have a look at this issue here?
https://github.com/gatsbyjs/gatsby/pull/2871

Also maybe this is of help for you:
https://github.com/gatsbyjs/gatsby/issues/1754

Did you install node-gyp correct? Did you try to redo the ``npm install``? If you're on windows you can also revisit this site:
https://www.gatsbyjs.org/docs/gatsby-on-windows/

**Comment by SKempin** [comment]
@LeKoArts I simply followed the README for this starter, and have been experiencing the issues since. I'm on Mac. Is there a conflict with this starter theme and the latest gatsby?

**Comment by LeKoArts** [comment]
No, I think it's not related to this theme or Gatsby itself but rather to the build environment respectively with some missing node.js modules.

> Many Gatsby plugins and themes require building native Node.js modules, e.g. Sharp (a common Gatsby dependency used for image processing). To do so, you need a functional build environment (Python and Visual C++ Build Tools).

As stated [here](https://www.gatsbyjs.org/docs/gatsby-on-windows/) you'll need some prerequisites to use e.g. Sharp. You should double-check if ``node-gyp`` is installed correctly:
https://github.com/nodejs/node-gyp#installation

**Comment by LeKoArts** [comment]
@jwgravesfl @SKempin 
Could you resolve the issue(s)?

**Comment by jwgravesfl** [comment]
I gave up.

Sent from BlueMail<http://www.bluemail.me/r?b=11061>
On Nov 17, 2017, at 4:23 AM, LekoArts <notifications@github.com<mailto:notifications@github.com>> wrote:

@jwgravesfl<https://github.com/jwgravesfl> @SKempin<https://github.com/skempin>
Could you resolve the issue(s)?

**Comment by SKempin** [comment]
@LeKoArts No I am still having the issue, even after checking node-gyp was installed correctly.

**Comment by LeKoArts** [comment]
As it's an external issue unrelated to this starter I'm closing this issue.

**Comment by jwgravesfl** [comment]
the problem for me was I needed to change python.exe to python2.7.exe
