### ISSUE TITLE
Jittery image load when browser not maximised

### ISSUE THREAD

**Issue by neo01124** [LekoArts/gatsby-starter-portfolio-emma#27]
Hi
Thanks for sharing this theme. All your themes are great.

This is the issue - https://streamable.com/z205s 
Where could I poke to fix this?

**Comment by LekoArts** [comment]
Sorry, but I can't reproduce this on my machine (Win 10, Chrome)

**Comment by neo01124** [comment]
Thanks. It stopped happening once I added more posts (>4). Closing until I run into it again.

**Comment by Anaizing** [comment]
Im having the same isuue, im also running Windows10 and Chrome...
